// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cppCalcPlayerTendencies
NumericVector cppCalcPlayerTendencies(NumericVector a, NumericVector b, NumericVector c);
RcppExport SEXP rhlstats_cppCalcPlayerTendencies(SEXP aSEXP, SEXP bSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    __result = Rcpp::wrap(cppCalcPlayerTendencies(a, b, c));
    return __result;
END_RCPP
}
