# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppCalcTryHard <- function(points, delPoints, tendtryHard) {
    .Call('rhlstats_cppCalcTryHard', PACKAGE = 'rhlstats', points, delPoints, tendtryHard)
}

cppCalcLifeTime <- function(uptimes, dailyTend, uptimeTend) {
    .Call('rhlstats_cppCalcLifeTime', PACKAGE = 'rhlstats', uptimes, dailyTend, uptimeTend)
}

cppCalcPlayerTendencies <- function(a, b, c) {
    .Call('rhlstats_cppCalcPlayerTendencies', PACKAGE = 'rhlstats', a, b, c)
}

