# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppCalcPlayerTendencies <- function(a, b, c) {
    .Call('rhlstats_cppCalcPlayerTendencies', PACKAGE = 'rhlstats', a, b, c)
}

